theme = "solarized-dark"

[icons]
name = "awesome"
[icons.overrides]
cpu = "\uf2db "
memory_mem = "\uf538 "
memory_swap = "\uf538 "

[[block]]
block = "focused_window"
max_width = 30

[[block]]
block = "net"
device = "wlp0s20f3"
ssid = false
signal_strength = true
ip = true
speed_up = true
graph_up = false
interval = 5
use_bits = false

[[block]]
block = "disk_space"
path = "/home/vik/"
alias = "/vik"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB"
format_swap = "{SUm}MB"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°"
chip = "*-isa-*"

[[block]]
block = "sound"

[[block]]
block = "battery"
# driver = "upower"
format = "{percentage}% {time} {power}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
