theme = "solarized-dark"


[icons]
name = "awesome"
[icons.overrides]
cpu = "\uf2db "
memory_mem = "\uf538 "
memory_swap = "\uf538 "
custom_wifi = "\uf1eb"
custom_nowifi = "\uf884"
custom_ethernet = "\uf6ff"
music = "\uf186"
custom_mic_on = "\uf130"
custom_mic_off = "\uf131"

[[block]]
block = "focused_window"
max_width = 30

[[block]]
block = "custom"
command = "~/.config/i3/scripts/i3-wifi-state"
json = true

[[block]]
block = "music"
buttons = ["prev", "play", "next"]

[[block]]
block = "disk_space"
path = "/home/vik/"
alias = "/vik"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB"
format_swap = "{SUm}MB"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°"
chip = "*-isa-*"

[[block]]
block = "custom"
on_click = "toggle-mic"
command = "~/.config/i3/scripts/mic-state"
json = true

[[block]]
block = "sound"

[[block]]
block = "battery"
# driver = "upower"
# format = "{percentage}% {time} {power}"
format = "{percentage}%"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
